# Multi-Agent Verification System Configuration
# This configuration demonstrates how to set up the advanced verification and reflection system

# Google ADK and A2A Configuration
google_adk:
  model: "gemini-2.0-flash"
  project_id: "your-google-cloud-project"
  credentials_path: "path/to/service-account.json"
  region: "us-central1"

# A2A Protocol Settings
a2a_protocol:
  agent_network_id: "nyxtrade-verification-network"
  consensus_threshold: 0.7  # Minimum consensus score to accept decision
  verification_timeout: 30  # Seconds to wait for verification
  reflection_threshold: 0.6  # Trigger reflection if consensus below this

# Multi-Agent Verification Configuration
verification_system:
  enabled: true
  
  # Primary Decision Agents
  primary_agents:
    market_analyzer:
      model: "gemini-2.0-flash"
      capabilities: ["technical_analysis", "price_prediction", "market_sentiment"]
      confidence_weight: 0.4
      
    risk_manager:
      model: "gemini-2.0-flash"
      capabilities: ["risk_assessment", "position_sizing", "portfolio_analysis"]
      confidence_weight: 0.3
      
    arbitrage_hunter:
      model: "gemini-2.0-flash"
      capabilities: ["arbitrage_detection", "cross_exchange_analysis"]
      confidence_weight: 0.2
      
    portfolio_manager:
      model: "gemini-2.0-flash"
      capabilities: ["asset_allocation", "rebalancing", "optimization"]
      confidence_weight: 0.1

  # Verification Agents
  verification_agents:
    technical_verifier:
      model: "gemini-2.0-flash"
      specialization: "technical_analysis"
      verification_weight: 0.35
      instruction: |
        You are a technical analysis verification specialist. Your role is to:
        1. Verify accuracy of technical indicators and calculations
        2. Check for misinterpretation of chart patterns
        3. Validate support/resistance level identification
        4. Ensure proper timeframe analysis
        5. Identify potential biases in technical analysis
        Be extremely critical and thorough in your verification.
        
    risk_verifier:
      model: "gemini-2.0-flash"
      specialization: "risk_management"
      verification_weight: 0.35
      instruction: |
        You are a risk assessment verification specialist. Your role is to:
        1. Verify risk calculation accuracy (VaR, Sharpe ratio, etc.)
        2. Challenge position sizing decisions
        3. Identify overlooked correlation risks
        4. Validate stress testing scenarios
        5. Ensure compliance with risk limits
        Prioritize capital preservation over profit maximization.
        
    market_verifier:
      model: "gemini-2.0-flash"
      specialization: "market_context"
      verification_weight: 0.30
      instruction: |
        You are a market context verification specialist. Your role is to:
        1. Verify market sentiment interpretation
        2. Cross-check news and social media analysis
        3. Validate macro-economic factor consideration
        4. Ensure comprehensive market context
        5. Identify potential sentiment biases
        Focus on objective market analysis and context validation.

  # Reflection Agent
  reflection_agent:
    model: "gemini-2.0-flash"
    learning_window: 100  # Number of past decisions to consider
    adaptation_rate: 0.1  # How quickly to adapt strategies
    instruction: |
      You are a trading decision reflection and learning specialist. Your role is to:
      1. Analyze patterns in successful and failed trading decisions
      2. Identify systematic biases and errors
      3. Suggest strategy improvements and adaptations
      4. Learn from market regime changes
      5. Provide alternative approaches when consensus is low
      Focus on continuous improvement and adaptive learning.

# Consensus Calculation Settings
consensus_calculation:
  method: "weighted_average"  # Options: simple_average, weighted_average, majority_vote
  
  # Weights for different verification aspects
  weights:
    accuracy_score: 0.4
    confidence_adjustment: 0.3
    verification_status: 0.2
    historical_performance: 0.1
  
  # Minimum requirements
  minimum_verifiers: 2
  minimum_accuracy: 0.6
  minimum_confidence: 0.5

# Reflection Triggers
reflection_triggers:
  low_consensus: 0.7  # Trigger if consensus below this
  high_uncertainty: 0.8  # Trigger if uncertainty above this
  conflicting_signals: true  # Trigger if agents disagree significantly
  poor_performance: true  # Trigger if recent performance is poor
  
# Learning and Adaptation
learning_system:
  enabled: true
  
  # Performance tracking
  performance_metrics:
    - "accuracy"
    - "profit_loss"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
  
  # Adaptation parameters
  adaptation:
    strategy_adjustment_threshold: 0.6  # Adjust if performance below this
    confidence_decay_rate: 0.05  # Reduce confidence over time if no validation
    learning_rate: 0.1  # How quickly to incorporate new learnings
    
  # Historical analysis
  historical_analysis:
    lookback_period: 30  # Days to analyze
    minimum_samples: 10  # Minimum decisions needed for analysis
    significance_threshold: 0.05  # Statistical significance level

# Agent Communication
agent_communication:
  message_timeout: 10  # Seconds
  retry_attempts: 3
  batch_processing: true
  
  # Message priorities
  priorities:
    emergency_stop: 4
    risk_alert: 3
    trade_signal: 2
    market_update: 1

# Monitoring and Alerting
monitoring:
  verification_metrics:
    - "consensus_score_distribution"
    - "verification_accuracy"
    - "reflection_trigger_frequency"
    - "agent_response_times"
    - "decision_confidence_trends"
  
  alerts:
    low_consensus_threshold: 0.5
    high_disagreement_threshold: 0.8
    agent_failure_threshold: 3  # Failed verifications
    
# Security and Validation
security:
  agent_authentication: true
  message_encryption: true
  audit_logging: true
  
  # Validation rules
  validation:
    max_position_size: 0.1  # 10% of portfolio
    max_daily_trades: 10
    min_confidence_for_execution: 0.6
    
# Performance Optimization
performance:
  parallel_verification: true
  caching_enabled: true
  cache_ttl: 300  # 5 minutes
  
  # Resource limits
  limits:
    max_concurrent_verifications: 5
    verification_timeout: 30
    reflection_timeout: 60
    
# Development and Testing
development:
  simulation_mode: true  # Use simulated data for testing
  debug_logging: true
  save_decision_history: true
  
  # Testing parameters
  testing:
    mock_agents: false
    deterministic_responses: false
    performance_benchmarking: true

# Integration Settings
integrations:
  # External data sources for verification
  data_sources:
    - "coingecko"
    - "messari"
    - "newsapi"
    - "twitter"
    
  # External validation services
  validation_services:
    - "tradingview_signals"
    - "crypto_fear_greed"
    - "on_chain_metrics"
